load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "phase_rotation",
    srcs = [
        "src/phase_rotation_utils.cpp",
    ],
    hdrs = [
        "include/everest/phase_rotation/phase_rotation_utils.hpp",
    ],
    copts = ["-std=c++17"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//lib/everest/framework:framework",
        "//types:types_lib",
    ],
)
