#!/usr/bin/env bash
# Tests `core` and `boundary` standalone.
#
# The crate depends on `everestrs`, whose bindings are generated by the CMake
# build into `$OUT_DIR`, so `cargo test` against the real manifest cannot
# resolve the dependency until the module is wired into CMake. Neither `core`
# nor `boundary` uses `everestrs`, so this copies `src/` without `src/main.rs`
# into a temporary directory, writes a `[lib]` only manifest carrying just the
# dependencies those two modules need, and tests there. Nothing is stubbed out.
set -euo pipefail

module_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
work_dir=$(mktemp -d)
trap 'rm -rf "${work_dir}"' EXIT

cp -r "${module_dir}/src" "${work_dir}/src"
rm -f "${work_dir}/src/main.rs"

# Versions match modules/EVSE/RsEvseManager/Cargo.toml.
cat >"${work_dir}/Cargo.toml" <<'MANIFEST'
[package]
name = "rs_evse_manager_core"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.82"
log = "0.4.20"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
proptest = "1.6.0"

[workspace]
MANIFEST

export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=cc
cd "${work_dir}"
cargo test --offline
cargo clippy --all-targets --offline -- -D warnings
