if(EVEREST_BUILD_BASE)
    add_subdirectory(log)
    add_subdirectory(timer)
    add_subdirectory(util)
    add_subdirectory(sqlite)
    add_subdirectory(evse_security)
    add_subdirectory(tls)
endif()

if(EVEREST_BUILD_ISO15118)
    add_subdirectory(cbv2g)
    add_subdirectory(iso15118)
endif()

if(EVEREST_BUILD_OCPP)
    add_subdirectory(ocpp)
endif()

if(EVEREST_BUILD_CORE)
    add_subdirectory(everest_api_module_helpers)
    add_subdirectory(everest_api_types)
    add_subdirectory(framework)
    add_subdirectory(helpers)
    add_subdirectory(ieee2030_1_1)
    add_subdirectory(io)
    add_subdirectory(run_application)
    add_subdirectory(yaml)
    if(EVEREST_DEPENDENCY_ENABLED_EVEREST_GPIO)
        add_subdirectory(gpio)
    endif()
    if(EVEREST_DEPENDENCY_ENABLED_SDBUS_CPP)
        add_subdirectory(system)
    endif()
endif()

if(EVEREST_BUILD_RUNTIME)
    add_subdirectory(can_dpm1000)
    add_subdirectory(conversions)
    add_subdirectory(crc)
    add_subdirectory(external_energy_limits)
    add_subdirectory(ocpp_module_common)
    add_subdirectory(slac)
endif()
