/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "lo2hi.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(LoToHi, LoToHi, AUTO)


PB_BIND(Event, Event, AUTO)


PB_BIND(Measurements, Measurements, AUTO)


PB_BIND(KeepAliveLo, KeepAliveLo, AUTO)


PB_BIND(ResetDone, ResetDone, AUTO)




