name: Documentation change
description: Suggest an optimization for the EVerest documentation.

body:
  - type: textarea
    id: description
    attributes:
      label: Describe your changes
      description: |
        Please describe, what the documentation change is about and eventually
        reference the related issue.
        If there are any connections to other GitHub repositories (e.g.
        similar or related documentation snippets or the source code / feature
        that is documented), please also reference them here.
    validations:
      required: true

  - type: textarea
    id: issue_nr
    attributes:
      label: Related issue (link)
      description: Please paste the reference to a related issue (optional).
    validations:
      required: false

  - type: dropdown
    id: change_type
    attributes:
      label: Type of change
      multiple: false
      description: Please select which describes your change best.
      options:
        - New documentation about an already existing software feature
        - Documentation for a non-published feature (currently
          work-in-progress).
        - Change / optimization of documentation

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Make sure to have respected the following aspects.
      options:
        - label: My documentation follows the docs style guidelines of this
          project.
          required: true
        - label: I have performed a self-review of my changes.
          required: true
        - label: I have checked potentially related repositories for related
          docs.
          required: true
