// SPDX-License-Identifier: Apache-2.0

#include <openssl/crypto.h>
#include <evse_security/crypto/openssl/ASN1_ctl.hpp>
#include <openssl/asn1.h>
#include <openssl/asn1t.h>
#include <openssl/err.h>
#include <openssl/safestack.h>

#include <cstring>
#include <memory>
#include <stdexcept>
#include <string>
#include <vector>

#include <evse_security/crypto/evse_crypto.hpp>
#include <evse_security/evse_types.hpp>


struct Asn1CtlValidity {
    ASN1_GENERALIZEDTIME* notBefore = nullptr;
    ASN1_GENERALIZEDTIME* notAfter  = nullptr;
};

struct Asn1CtlRootEntry {
    ASN1_ENUMERATED*   certificateType = nullptr;
    ASN1_ENUMERATED*   ctlStatus       = nullptr;
    ASN1_OCTET_STRING* certificate     = nullptr;   // DER-encoded X.509
};

DEFINE_STACK_OF(Asn1CtlRootEntry)

struct Asn1CtlEvpkiCtl {
    ASN1_INTEGER*                 ctlVersion       = nullptr;
    ASN1_INTEGER*                 sequenceNumber   = nullptr;
    Asn1CtlValidity*              validity         = nullptr;
    STACK_OF(Asn1CtlRootEntry)*   rootCertificates = nullptr;
};

ASN1_SEQUENCE(Asn1CtlValidity) = {
    ASN1_SIMPLE(Asn1CtlValidity, notBefore, ASN1_GENERALIZEDTIME),
    ASN1_SIMPLE(Asn1CtlValidity, notAfter,  ASN1_GENERALIZEDTIME)
} ASN1_SEQUENCE_END(Asn1CtlValidity)
IMPLEMENT_ASN1_FUNCTIONS(Asn1CtlValidity)

ASN1_SEQUENCE(Asn1CtlRootEntry) = {
    ASN1_SIMPLE(Asn1CtlRootEntry, certificateType, ASN1_ENUMERATED),
    ASN1_SIMPLE(Asn1CtlRootEntry, ctlStatus,       ASN1_ENUMERATED),
    ASN1_SIMPLE(Asn1CtlRootEntry, certificate,     ASN1_OCTET_STRING)
} ASN1_SEQUENCE_END(Asn1CtlRootEntry)
IMPLEMENT_ASN1_FUNCTIONS(Asn1CtlRootEntry)

ASN1_SEQUENCE(Asn1CtlEvpkiCtl) = {
    ASN1_SIMPLE(Asn1CtlEvpkiCtl, ctlVersion,     ASN1_INTEGER),
    ASN1_SIMPLE(Asn1CtlEvpkiCtl, sequenceNumber, ASN1_INTEGER),
    ASN1_SIMPLE(Asn1CtlEvpkiCtl, validity,       Asn1CtlValidity),
    ASN1_SEQUENCE_OF(Asn1CtlEvpkiCtl, rootCertificates, Asn1CtlRootEntry)
} ASN1_SEQUENCE_END(Asn1CtlEvpkiCtl)
IMPLEMENT_ASN1_FUNCTIONS(Asn1CtlEvpkiCtl)


namespace ctl {

using evse_security::CryptoSupplier;
using evse_security::EncodingFormat;
using evse_security::CaCertificateType;

namespace {

CaCertificateType wire_to_ca_type(long wire) {
    switch (wire) {
    case 0: return CaCertificateType::V2G;    // v2g
    case 1: return CaCertificateType::MF;     // oem
    case 2: return CaCertificateType::MO;     // msp
    case 3: return CaCertificateType::CSMS;   // other
    default:
        throw std::runtime_error("unknown CTL certificateType: " +
                                 std::to_string(wire));
    }
}

long ca_type_to_wire(CaCertificateType t) {
    switch (t) {
    case CaCertificateType::V2G:  return 0;
    case CaCertificateType::MF:   return 1;
    case CaCertificateType::MO:   return 2;
    case CaCertificateType::CSMS: return 3;
    }
    throw std::runtime_error("CaCertificateType has no CTL wire value");
}

// RAII wrappers for the ASN.1 objects. These use the real functions
// generated by IMPLEMENT_ASN1_FUNCTIONS, so taking their address is legal.
using ValidityPtr = std::unique_ptr<Asn1CtlValidity,  decltype(&Asn1CtlValidity_free)>;
using RootPtr     = std::unique_ptr<Asn1CtlRootEntry, decltype(&Asn1CtlRootEntry_free)>;
using CtlPtr      = std::unique_ptr<Asn1CtlEvpkiCtl,  decltype(&Asn1CtlEvpkiCtl_free)>;

CtlPtr to_asn1(const TrustList& src) {
    CtlPtr a(Asn1CtlEvpkiCtl_new(), &Asn1CtlEvpkiCtl_free);
    if (!a) {
        throw std::runtime_error("Asn1CtlEvpkiCtl_new failed");
    }

    if (ASN1_INTEGER_set(a->ctlVersion,     src.ctl_version)     != 1 ||
        ASN1_INTEGER_set(a->sequenceNumber, src.sequence_number) != 1) {
        throw std::runtime_error("ASN1_INTEGER_set failed");
    }

    if (ASN1_GENERALIZEDTIME_set_string(a->validity->notBefore,
                                        src.not_before.value.c_str()) != 1 ||
        ASN1_GENERALIZEDTIME_set_string(a->validity->notAfter,
                                        src.not_after.value.c_str())  != 1) {
        throw std::runtime_error("ASN1_GENERALIZEDTIME_set_string failed");
    }

    for (const auto& r : src.roots) {
        RootPtr e(Asn1CtlRootEntry_new(), &Asn1CtlRootEntry_free);
        if (!e) {
            throw std::runtime_error("Asn1CtlRootEntry_new failed");
        }

        // Single translation point: CaCertificateType -> wire enum.
        ASN1_ENUMERATED_set(e->certificateType, ca_type_to_wire(r.type));
        ASN1_ENUMERATED_set(e->ctlStatus,       static_cast<long>(r.status));

        // Chain through the crypto supplier for the cert blob.
        std::vector<std::uint8_t> der;
        if (!CryptoSupplier::x509_to_der(r.cert.get(), der)) {
            throw std::runtime_error("CryptoSupplier::x509_to_der failed");
        }

        if (ASN1_STRING_set(e->certificate, der.data(),
                            static_cast<int>(der.size())) != 1) {
            throw std::runtime_error("ASN1_STRING_set failed");
        }

        if (sk_Asn1CtlRootEntry_push(a->rootCertificates, e.get()) == 0) {
            throw std::runtime_error("sk_Asn1CtlRootEntry_push failed");
        }
        e.release();   // stack now owns it
    }

    return a;
}

TrustList from_asn1(const Asn1CtlEvpkiCtl& a) {
    TrustList dst;
    dst.ctl_version     = static_cast<std::uint8_t >(ASN1_INTEGER_get(a.ctlVersion));
    dst.sequence_number = static_cast<std::uint16_t>(ASN1_INTEGER_get(a.sequenceNumber));

    const char* nb = reinterpret_cast<const char*>(a.validity->notBefore->data);
    const char* na = reinterpret_cast<const char*>(a.validity->notAfter->data);
    if (!nb || !na || std::strlen(nb) != 15 || std::strlen(na) != 15) {
        throw std::runtime_error("bad GeneralizedTime length");
    }
    dst.not_before.value.assign(nb, 15);
    dst.not_after.value.assign(na, 15);

    const int n = sk_Asn1CtlRootEntry_num(a.rootCertificates);
    dst.roots.reserve(static_cast<std::size_t>(n));

    for (int i = 0; i < n; ++i) {
        const Asn1CtlRootEntry* e = sk_Asn1CtlRootEntry_value(a.rootCertificates, i);

        // OCTET STRING contents are DER-encoded X.509.
        const std::string cert_der(
            reinterpret_cast<const char*>(e->certificate->data),
            static_cast<std::size_t>(e->certificate->length));

        auto handles = CryptoSupplier::load_certificates(cert_der, EncodingFormat::DER);
        if (handles.size() != 1) {
            throw std::runtime_error("expected exactly one DER certificate in CTL entry");
        }

        RootCertificate root{
            // Single translation point: wire enum -> CaCertificateType.
            wire_to_ca_type(ASN1_ENUMERATED_get(e->certificateType)),
            static_cast<Status>(ASN1_ENUMERATED_get(e->ctlStatus)),
            evse_security::X509Wrapper(std::move(handles[0]))
        };
        dst.roots.push_back(std::move(root));
    }

    return dst;
}

} // namespace

// ---------------------------------------------------------------
//  Public API
// ---------------------------------------------------------------

std::vector<std::uint8_t> encode_der(const TrustList& ctl) {
    CtlPtr a = to_asn1(ctl);

    unsigned char* raw = nullptr;
    const int len = i2d_Asn1CtlEvpkiCtl(a.get(), &raw);
    if (len <= 0 || raw == nullptr) {
        throw std::runtime_error("i2d_Asn1CtlEvpkiCtl failed");
    }

    std::vector<std::uint8_t> out(raw, raw + len);
    OPENSSL_free(raw);
    return out;
}

TrustList decode_der(const std::uint8_t* der, std::size_t len) {
    if (!der || len == 0) {
        throw std::runtime_error("empty input");
    }

    const unsigned char* p = der;
    CtlPtr a(d2i_Asn1CtlEvpkiCtl(nullptr, &p, static_cast<long>(len)),
             &Asn1CtlEvpkiCtl_free);
    if (!a) {
        throw std::runtime_error("d2i_Asn1CtlEvpkiCtl failed");
    }
    if (p != der + len) {
        throw std::runtime_error("trailing bytes after CTL");
    }

    return from_asn1(*a);
}

TrustList decode_der(const std::vector<std::uint8_t>& der) {
    return decode_der(der.data(), der.size());
}

} // namespace ctl