function(everest_read_expected_and_create_actual_hash_csv_files expected_hashes_file project_src_folder actual_hashes_file)
  file(STRINGS ${expected_hashes_file} EXPECTED_LINES)

  set(ACTUAL_HASHES_CSV_CONTENT "")
  foreach(LINE ${EXPECTED_LINES})
      string(STRIP "${LINE}" LINE)
      if(LINE STREQUAL "" OR LINE MATCHES "^#")
        string(APPEND ACTUAL_HASHES_CSV_CONTENT "${LINE}\n")
        continue()
      else()
        set(CSV_REGEX "^[^,]+,([^,]+),(.+)$")
        if(LINE MATCHES "${CSV_REGEX}")
          set(TRACKING_STATUS "${CMAKE_MATCH_1}")
          set(FILENAME "${CMAKE_MATCH_2}")
        else()
          message(FATAL_ERROR "Line '${LINE}' in '${expected_hashes_file}' does not match the expected '<hash>,<TRACKING|___no___>,<filename>' format")
        endif()
        #string(REGEX MATCH "^[^,]+" FILENAME ${LINE})

        set(FILE_PATH "${project_src_folder}/${FILENAME}")

        if(EXISTS ${FILE_PATH})
            if (TRACKING_STATUS STREQUAL "TRACKING")
              file(SHA256 ${FILE_PATH} ACTUAL_HASH)
            else()
              set(ACTUAL_HASH "0000000000000000000000000000000000000000000000000000000000000000")
            endif()
            string(APPEND ACTUAL_HASHES_CSV_CONTENT "${ACTUAL_HASH},${TRACKING_STATUS},${FILENAME}\n")
        else()
            # If a file listed in the CSV is missing, fail verbosely
            message(FATAL_ERROR "File '${FILENAME}' listed in '${expected_hashes_file}' was not found in '${project_src_folder}'.")
        endif()
      endif()
  endforeach()

  file(WRITE ${actual_hashes_file} "${ACTUAL_HASHES_CSV_CONTENT}")
endfunction()

everest_read_expected_and_create_actual_hash_csv_files(${EXPECTED_CSV} ${PROJECT_SRC_FOLDER} ${ACTUAL_CSV})
