-- Migration 4 rollback: remove multi-config support.
-- If multiple configs exist only the one with the lowest ID (the original migrated config) is kept.
-- All data belonging to other configs is discarded.
-- Note: ManagerSettings are not restored since they were never stored from migration 4 onward.

PRAGMA foreign_keys = OFF;

-- Determine the config to keep (lowest ID = the original pre-migration config).
-- We work backwards through the dependency chain so we don't violate constraints.

-- 8. MODULE_CONFIG_ACCESS
CREATE TABLE MODULE_CONFIG_ACCESS_NEW (
    MODULE_ID           TEXT,
    OTHER_MODULE_ID     TEXT,
    ALLOW_READ          INTEGER,
    ALLOW_WRITE         INTEGER,
    ALLOW_SET_READ_ONLY INTEGER,
    PRIMARY KEY (MODULE_ID),
    FOREIGN KEY (MODULE_ID)       REFERENCES MODULE (ID) ON DELETE CASCADE,
    FOREIGN KEY (OTHER_MODULE_ID) REFERENCES MODULE (ID) ON DELETE CASCADE
);
INSERT INTO MODULE_CONFIG_ACCESS_NEW
    SELECT MODULE_ID, OTHER_MODULE_ID, ALLOW_READ, ALLOW_WRITE, ALLOW_SET_READ_ONLY
    FROM MODULE_CONFIG_ACCESS
    WHERE CONFIG_ID = (SELECT MIN(ID) FROM CONFIG);
DROP TABLE MODULE_CONFIG_ACCESS;
ALTER TABLE MODULE_CONFIG_ACCESS_NEW RENAME TO MODULE_CONFIG_ACCESS;

-- 7. CONFIG_ACCESS
CREATE TABLE CONFIG_ACCESS_NEW (
    MODULE_ID           TEXT,
    ALLOW_GLOBAL_READ   INTEGER,
    ALLOW_GLOBAL_WRITE  INTEGER,
    ALLOW_SET_READ_ONLY INTEGER,
    PRIMARY KEY (MODULE_ID),
    FOREIGN KEY (MODULE_ID) REFERENCES MODULE (ID) ON DELETE CASCADE
);
INSERT INTO CONFIG_ACCESS_NEW
    SELECT MODULE_ID, ALLOW_GLOBAL_READ, ALLOW_GLOBAL_WRITE, ALLOW_SET_READ_ONLY
    FROM CONFIG_ACCESS
    WHERE CONFIG_ID = (SELECT MIN(ID) FROM CONFIG);
DROP TABLE CONFIG_ACCESS;
ALTER TABLE CONFIG_ACCESS_NEW RENAME TO CONFIG_ACCESS;

-- 6. CONFIGURATION
CREATE TABLE CONFIGURATION_NEW (
    PARAMETER_NAME           TEXT,
    MODULE_ID                TEXT    NOT NULL,
    MODULE_IMPLEMENTATION_ID TEXT    NOT NULL,
    "VALUE"                  TEXT    NOT NULL,
    MUTABILITY_ID            INTEGER NOT NULL,
    DATATYPE_ID              INTEGER NOT NULL,
    UNIT                     TEXT,
    SOURCE                   TEXT,
    PRIMARY KEY (MODULE_ID, PARAMETER_NAME, MODULE_IMPLEMENTATION_ID),
    FOREIGN KEY (MODULE_ID)     REFERENCES MODULE (ID)     ON DELETE CASCADE,
    FOREIGN KEY (DATATYPE_ID)   REFERENCES DATATYPE (ID)   ON DELETE RESTRICT,
    FOREIGN KEY (MUTABILITY_ID) REFERENCES MUTABILITY (ID) ON DELETE RESTRICT
);
INSERT INTO CONFIGURATION_NEW
    SELECT PARAMETER_NAME, MODULE_ID, MODULE_IMPLEMENTATION_ID, VALUE,
           MUTABILITY_ID, DATATYPE_ID, UNIT, SOURCE
    FROM CONFIGURATION
    WHERE CONFIG_ID = (SELECT MIN(ID) FROM CONFIG);
DROP TABLE CONFIGURATION;
ALTER TABLE CONFIGURATION_NEW RENAME TO CONFIGURATION;

-- 5. MODULE_TIER_MAPPING
CREATE TABLE MODULE_TIER_MAPPING_NEW (
    MODULE_ID         TEXT,
    IMPLEMENTATION_ID TEXT    NOT NULL,
    EVSE_ID           INTEGER NOT NULL,
    CONNECTOR_ID      INTEGER,
    PRIMARY KEY (MODULE_ID, IMPLEMENTATION_ID),
    FOREIGN KEY (MODULE_ID) REFERENCES MODULE (ID) ON DELETE CASCADE
);
INSERT INTO MODULE_TIER_MAPPING_NEW
    SELECT MODULE_ID, IMPLEMENTATION_ID, EVSE_ID, CONNECTOR_ID
    FROM MODULE_TIER_MAPPING
    WHERE CONFIG_ID = (SELECT MIN(ID) FROM CONFIG);
DROP TABLE MODULE_TIER_MAPPING;
ALTER TABLE MODULE_TIER_MAPPING_NEW RENAME TO MODULE_TIER_MAPPING;

-- 4. MODULE_FULFILLMENT
CREATE TABLE MODULE_FULFILLMENT_NEW (
    MODULE_ID                TEXT,
    REQUIREMENT_NAME         TEXT NOT NULL,
    IMPLEMENTATION_ID        TEXT NOT NULL,
    IMPLEMENTATION_MODULE_ID TEXT NOT NULL,
    PRIMARY KEY (MODULE_ID, REQUIREMENT_NAME, IMPLEMENTATION_ID, IMPLEMENTATION_MODULE_ID),
    FOREIGN KEY (MODULE_ID)                REFERENCES MODULE (ID) ON DELETE CASCADE,
    FOREIGN KEY (IMPLEMENTATION_MODULE_ID) REFERENCES MODULE (ID) ON DELETE CASCADE
);
INSERT INTO MODULE_FULFILLMENT_NEW
    SELECT MODULE_ID, REQUIREMENT_NAME, IMPLEMENTATION_ID, IMPLEMENTATION_MODULE_ID
    FROM MODULE_FULFILLMENT
    WHERE CONFIG_ID = (SELECT MIN(ID) FROM CONFIG);
DROP TABLE MODULE_FULFILLMENT;
ALTER TABLE MODULE_FULFILLMENT_NEW RENAME TO MODULE_FULFILLMENT;

-- 3. MODULE
CREATE TABLE MODULE_NEW (
    ID           TEXT PRIMARY KEY,
    NAME         TEXT    NOT NULL,
    STANDALONE   INTEGER,
    CAPABILITIES TEXT
);
INSERT INTO MODULE_NEW
    SELECT ID, NAME, STANDALONE, CAPABILITIES
    FROM MODULE
    WHERE CONFIG_ID = (SELECT MIN(ID) FROM CONFIG);
DROP TABLE MODULE;
ALTER TABLE MODULE_NEW RENAME TO MODULE;

-- 2. CONFIG_META: restore without FK, remap lowest CONFIG_ID back to ID=0.
CREATE TABLE CONFIG_META_NEW (
    ID               INTEGER PRIMARY KEY,
    LAST_UPDATED     TEXT    NOT NULL,
    VALID            TEXT    INTEGER NOT NULL,
    CONFIG_DUMP      TEXT    NOT NULL,
    CONFIG_FILE_PATH TEXT
);
INSERT INTO CONFIG_META_NEW
    SELECT 0, LAST_UPDATED, VALID, CONFIG_DUMP, CONFIG_FILE_PATH
    FROM CONFIG_META
    WHERE ID = (SELECT MIN(ID) FROM CONFIG);
DROP TABLE CONFIG_META;
ALTER TABLE CONFIG_META_NEW RENAME TO CONFIG_META;

-- 1. SETTING: restore with id=0 constraint and a default empty row.
--    ManagerSettings were not stored in the database from migration 4 onward,
--    so we recreate the table structure with defaults only.
CREATE TABLE SETTING_NEW (
    ID                        INTEGER PRIMARY KEY CHECK (id = 0),
    PREFIX                    TEXT    NOT NULL DEFAULT '',
    CONFIG_FILE               TEXT    NOT NULL DEFAULT '',
    CONFIGS_DIR               TEXT    NOT NULL DEFAULT '',
    SCHEMAS_DIR               TEXT    NOT NULL DEFAULT '',
    MODULES_DIR               TEXT    NOT NULL DEFAULT '',
    INTERFACES_DIR            TEXT    NOT NULL DEFAULT '',
    TYPES_DIR                 TEXT    NOT NULL DEFAULT '',
    ERRORS_DIR                TEXT    NOT NULL DEFAULT '',
    WWW_DIR                   TEXT    NOT NULL DEFAULT '',
    LOGGING_CONFIG_FILE       TEXT    NOT NULL DEFAULT '',
    CONTROLLER_PORT           INTEGER NOT NULL DEFAULT 0,
    CONTROLLER_RPC_TIMEOUT_MS INTEGER NOT NULL DEFAULT 0,
    MQTT_BROKER_SOCKET_PATH   TEXT    NOT NULL DEFAULT '',
    MQTT_BROKER_HOST          TEXT    NOT NULL DEFAULT '',
    MQTT_BROKER_PORT          INTEGER NOT NULL DEFAULT 0,
    MQTT_EVEREST_PREFIX       TEXT    NOT NULL DEFAULT '',
    MQTT_EXTERNAL_PREFIX      TEXT    NOT NULL DEFAULT '',
    TELEMETRY_PREFIX          TEXT    NOT NULL DEFAULT '',
    TELEMETRY_ENABLED         INTEGER NOT NULL DEFAULT 0,
    VALIDATE_SCHEMA           INTEGER NOT NULL DEFAULT 0,
    RUN_AS_USER               TEXT    NOT NULL DEFAULT '',
    FORWARD_EXCEPTIONS        INTEGER NOT NULL DEFAULT 0
);
INSERT OR IGNORE INTO SETTING_NEW (ID) VALUES (0);
DROP TABLE CONFIG;
ALTER TABLE SETTING_NEW RENAME TO SETTING;

PRAGMA foreign_keys = ON;
