ALTER TABLE SETTING DROP COLUMN SHM_TOPIC_REGISTRY_MODE;
ALTER TABLE SETTING DROP COLUMN SHM_TOPIC_REGISTRY_CAPACITY;
ALTER TABLE SETTING DROP COLUMN SHM_TOPIC_SLOT_SIZE;
ALTER TABLE SETTING DROP COLUMN SHM_TOPIC_SLOTS;
ALTER TABLE SETTING DROP COLUMN SHM_CONTROL_SOCKET_PATH;
ALTER TABLE SETTING DROP COLUMN FRAMEWORK_TRANSPORT;
