ALTER TABLE SETTING ADD COLUMN FRAMEWORK_TRANSPORT TEXT NOT NULL DEFAULT 'mqtt';
ALTER TABLE SETTING ADD COLUMN SHM_CONTROL_SOCKET_PATH TEXT NOT NULL DEFAULT '';
ALTER TABLE SETTING ADD COLUMN SHM_TOPIC_SLOTS INTEGER NOT NULL DEFAULT 8;
ALTER TABLE SETTING ADD COLUMN SHM_TOPIC_SLOT_SIZE INTEGER NOT NULL DEFAULT 65536;
ALTER TABLE SETTING ADD COLUMN SHM_TOPIC_REGISTRY_CAPACITY INTEGER NOT NULL DEFAULT 1024;
ALTER TABLE SETTING ADD COLUMN SHM_TOPIC_REGISTRY_MODE TEXT NOT NULL DEFAULT 'static';
