-- Migration 4: Multi-config support
-- Replaces SETTING with CONFIG (lightweight identity anchor).
-- ManagerSettings (paths, MQTT, controller settings) are no longer stored in the
-- database
-- Removes the single-row restriction so multiple configs can coexist.
-- Adds CONFIG_ID scoping to MODULE and all its child tables, with cascading deletes
-- rooted at CONFIG so that deleting a CONFIG row removes everything belonging to it.

PRAGMA foreign_keys = OFF;

-- 1. CONFIG: lightweight identity table - replaces SETTING as the cascade root.
CREATE TABLE CONFIG (
    ID INTEGER PRIMARY KEY
);
INSERT INTO CONFIG (ID) SELECT ID FROM SETTING;

DROP TABLE SETTING;

-- 2. CONFIG_META: update FK from SETTING to CONFIG.
CREATE TABLE CONFIG_META_NEW (
    ID               INTEGER PRIMARY KEY REFERENCES CONFIG (ID) ON DELETE CASCADE,
    LAST_UPDATED     TEXT    NOT NULL,
    VALID            INTEGER NOT NULL,
    CONFIG_DUMP      TEXT    NOT NULL,
    CONFIG_FILE_PATH TEXT
);
INSERT INTO CONFIG_META_NEW SELECT * FROM CONFIG_META;
DROP TABLE CONFIG_META;
ALTER TABLE CONFIG_META_NEW RENAME TO CONFIG_META;

-- 3. MODULE: add CONFIG_ID, composite PK (CONFIG_ID, ID). FK references CONFIG.
CREATE TABLE MODULE_NEW (
    CONFIG_ID    INTEGER NOT NULL REFERENCES CONFIG (ID) ON DELETE CASCADE,
    ID           TEXT    NOT NULL,
    NAME         TEXT    NOT NULL,
    STANDALONE   INTEGER,
    CAPABILITIES TEXT,
    PRIMARY KEY (CONFIG_ID, ID)
);
INSERT INTO MODULE_NEW SELECT 0, ID, NAME, STANDALONE, CAPABILITIES FROM MODULE;
DROP TABLE MODULE;
ALTER TABLE MODULE_NEW RENAME TO MODULE;

-- 4. MODULE_FULFILLMENT: composite FK on (CONFIG_ID, MODULE_ID) and (CONFIG_ID, IMPLEMENTATION_MODULE_ID).
CREATE TABLE MODULE_FULFILLMENT_NEW (
    CONFIG_ID                INTEGER NOT NULL,
    MODULE_ID                TEXT    NOT NULL,
    REQUIREMENT_NAME         TEXT    NOT NULL,
    IMPLEMENTATION_ID        TEXT    NOT NULL,
    IMPLEMENTATION_MODULE_ID TEXT    NOT NULL,
    PRIMARY KEY (CONFIG_ID, MODULE_ID, REQUIREMENT_NAME, IMPLEMENTATION_ID, IMPLEMENTATION_MODULE_ID),
    FOREIGN KEY (CONFIG_ID, MODULE_ID)                REFERENCES MODULE (CONFIG_ID, ID) ON DELETE CASCADE,
    FOREIGN KEY (CONFIG_ID, IMPLEMENTATION_MODULE_ID) REFERENCES MODULE (CONFIG_ID, ID) ON DELETE CASCADE
);
INSERT INTO MODULE_FULFILLMENT_NEW
    SELECT 0, MODULE_ID, REQUIREMENT_NAME, IMPLEMENTATION_ID, IMPLEMENTATION_MODULE_ID
    FROM MODULE_FULFILLMENT;
DROP TABLE MODULE_FULFILLMENT;
ALTER TABLE MODULE_FULFILLMENT_NEW RENAME TO MODULE_FULFILLMENT;

-- 5. MODULE_TIER_MAPPING: composite FK on (CONFIG_ID, MODULE_ID).
CREATE TABLE MODULE_TIER_MAPPING_NEW (
    CONFIG_ID         INTEGER NOT NULL,
    MODULE_ID         TEXT    NOT NULL,
    IMPLEMENTATION_ID TEXT    NOT NULL,
    EVSE_ID           INTEGER NOT NULL,
    CONNECTOR_ID      INTEGER,
    PRIMARY KEY (CONFIG_ID, MODULE_ID, IMPLEMENTATION_ID),
    FOREIGN KEY (CONFIG_ID, MODULE_ID) REFERENCES MODULE (CONFIG_ID, ID) ON DELETE CASCADE
);
INSERT INTO MODULE_TIER_MAPPING_NEW
    SELECT 0, MODULE_ID, IMPLEMENTATION_ID, EVSE_ID, CONNECTOR_ID
    FROM MODULE_TIER_MAPPING;
DROP TABLE MODULE_TIER_MAPPING;
ALTER TABLE MODULE_TIER_MAPPING_NEW RENAME TO MODULE_TIER_MAPPING;

-- 6. CONFIGURATION: composite FK on (CONFIG_ID, MODULE_ID).
CREATE TABLE CONFIGURATION_NEW (
    CONFIG_ID                INTEGER NOT NULL,
    PARAMETER_NAME           TEXT    NOT NULL,
    MODULE_ID                TEXT    NOT NULL,
    MODULE_IMPLEMENTATION_ID TEXT    NOT NULL,
    "VALUE"                  TEXT    NOT NULL,
    MUTABILITY_ID            INTEGER NOT NULL,
    DATATYPE_ID              INTEGER NOT NULL,
    UNIT                     TEXT,
    SOURCE                   TEXT,
    PRIMARY KEY (CONFIG_ID, MODULE_ID, PARAMETER_NAME, MODULE_IMPLEMENTATION_ID),
    FOREIGN KEY (CONFIG_ID, MODULE_ID) REFERENCES MODULE (CONFIG_ID, ID) ON DELETE CASCADE,
    FOREIGN KEY (DATATYPE_ID)          REFERENCES DATATYPE (ID)  ON DELETE RESTRICT,
    FOREIGN KEY (MUTABILITY_ID)        REFERENCES MUTABILITY (ID) ON DELETE RESTRICT
);
INSERT INTO CONFIGURATION_NEW
    SELECT 0, PARAMETER_NAME, MODULE_ID, MODULE_IMPLEMENTATION_ID, VALUE,
           MUTABILITY_ID, DATATYPE_ID, UNIT, SOURCE
    FROM CONFIGURATION;
DROP TABLE CONFIGURATION;
ALTER TABLE CONFIGURATION_NEW RENAME TO CONFIGURATION;

-- 7. CONFIG_ACCESS: composite FK on (CONFIG_ID, MODULE_ID).
CREATE TABLE CONFIG_ACCESS_NEW (
    CONFIG_ID           INTEGER NOT NULL,
    MODULE_ID           TEXT    NOT NULL,
    ALLOW_GLOBAL_READ   INTEGER,
    ALLOW_GLOBAL_WRITE  INTEGER,
    ALLOW_SET_READ_ONLY INTEGER,
    PRIMARY KEY (CONFIG_ID, MODULE_ID),
    FOREIGN KEY (CONFIG_ID, MODULE_ID) REFERENCES MODULE (CONFIG_ID, ID) ON DELETE CASCADE
);
INSERT INTO CONFIG_ACCESS_NEW
    SELECT 0, MODULE_ID, ALLOW_GLOBAL_READ, ALLOW_GLOBAL_WRITE, ALLOW_SET_READ_ONLY
    FROM CONFIG_ACCESS;
DROP TABLE CONFIG_ACCESS;
ALTER TABLE CONFIG_ACCESS_NEW RENAME TO CONFIG_ACCESS;

-- 8. MODULE_CONFIG_ACCESS: composite FKs on both MODULE_ID and OTHER_MODULE_ID.
CREATE TABLE MODULE_CONFIG_ACCESS_NEW (
    CONFIG_ID           INTEGER NOT NULL,
    MODULE_ID           TEXT    NOT NULL,
    OTHER_MODULE_ID     TEXT    NOT NULL,
    ALLOW_READ          INTEGER,
    ALLOW_WRITE         INTEGER,
    ALLOW_SET_READ_ONLY INTEGER,
    PRIMARY KEY (CONFIG_ID, MODULE_ID, OTHER_MODULE_ID),
    FOREIGN KEY (CONFIG_ID, MODULE_ID)       REFERENCES MODULE (CONFIG_ID, ID) ON DELETE CASCADE,
    FOREIGN KEY (CONFIG_ID, OTHER_MODULE_ID) REFERENCES MODULE (CONFIG_ID, ID) ON DELETE CASCADE
);
INSERT INTO MODULE_CONFIG_ACCESS_NEW
    SELECT 0, MODULE_ID, OTHER_MODULE_ID, ALLOW_READ, ALLOW_WRITE, ALLOW_SET_READ_ONLY
    FROM MODULE_CONFIG_ACCESS;
DROP TABLE MODULE_CONFIG_ACCESS;
ALTER TABLE MODULE_CONFIG_ACCESS_NEW RENAME TO MODULE_CONFIG_ACCESS;

PRAGMA foreign_keys = ON;
