-- Migration 4: Multi-config support
-- Replaces SETTING with CONFIG (lightweight identity anchor).
-- ManagerSettings (paths, MQTT, controller settings) are no longer stored in the
-- database
-- Removes the single-row restriction so multiple configs can coexist.
-- Adds CONFIG_ID scoping to MODULE and all its child tables, with cascading deletes
-- rooted at CONFIG so that deleting a CONFIG row removes everything belonging to it.
-- fix Mutability and Datatype tables
--
-- NOTE: foreign-key enforcement is disabled by the SchemaUpdater for the duration of the
-- migration transaction ("PRAGMA foreign_keys" would be a no-op inside it).

-- 0. Remove configs marked invalid. FK enforcement is off during migration,
--    so ON DELETE CASCADE does not fire — delete children explicitly.
DELETE FROM MODULE_FULFILLMENT   WHERE EXISTS (SELECT 1 FROM CONFIG_META WHERE VALID = 0);
DELETE FROM MODULE_TIER_MAPPING  WHERE EXISTS (SELECT 1 FROM CONFIG_META WHERE VALID = 0);
DELETE FROM CONFIGURATION        WHERE EXISTS (SELECT 1 FROM CONFIG_META WHERE VALID = 0);
DELETE FROM CONFIG_ACCESS        WHERE EXISTS (SELECT 1 FROM CONFIG_META WHERE VALID = 0);
DELETE FROM MODULE_CONFIG_ACCESS WHERE EXISTS (SELECT 1 FROM CONFIG_META WHERE VALID = 0);
DELETE FROM MODULE               WHERE EXISTS (SELECT 1 FROM CONFIG_META WHERE VALID = 0);
DELETE FROM CONFIG_META          WHERE VALID = 0;
DELETE FROM SETTING              WHERE NOT EXISTS (SELECT 1 FROM CONFIG_META);

-- 1. CONFIG: lightweight identity table - replaces SETTING as the cascade root.
CREATE TABLE CONFIG (
    ID INTEGER PRIMARY KEY
);
INSERT INTO CONFIG (ID) SELECT ID FROM SETTING;

DROP TABLE SETTING;

-- 2. CONFIG_META: update FK from SETTING to CONFIG; add DESCRIPTION column.
CREATE TABLE CONFIG_META_NEW (
    ID               INTEGER PRIMARY KEY REFERENCES CONFIG (ID) ON DELETE CASCADE,
    LAST_UPDATED     TEXT    NOT NULL,
    CONFIG_DUMP      TEXT    NOT NULL,
    CONFIG_FILE_PATH TEXT,
    DESCRIPTION      TEXT
);
INSERT INTO CONFIG_META_NEW SELECT ID, LAST_UPDATED, CONFIG_DUMP, CONFIG_FILE_PATH, NULL FROM CONFIG_META;
DROP TABLE CONFIG_META;
ALTER TABLE CONFIG_META_NEW RENAME TO CONFIG_META;

-- 3. MODULE: add CONFIG_ID, composite PK (CONFIG_ID, ID). FK references CONFIG.
CREATE TABLE MODULE_NEW (
    CONFIG_ID    INTEGER NOT NULL REFERENCES CONFIG (ID) ON DELETE CASCADE,
    ID           TEXT    NOT NULL,
    NAME         TEXT    NOT NULL,
    STANDALONE   INTEGER,
    CAPABILITIES TEXT,
    PRIMARY KEY (CONFIG_ID, ID)
);
INSERT INTO MODULE_NEW SELECT 0, ID, NAME, STANDALONE, CAPABILITIES FROM MODULE;
DROP TABLE MODULE;
ALTER TABLE MODULE_NEW RENAME TO MODULE;

-- 4. MODULE_FULFILLMENT: composite FK on (CONFIG_ID, MODULE_ID) and (CONFIG_ID, IMPLEMENTATION_MODULE_ID).
-- REQUIREMENT_INDEX stores the position of a fulfillment within its requirement, as listed in the
-- config. Requirements are resolved positionally (see Requirement::index), so this order has to
-- survive the round trip through the database.
CREATE TABLE MODULE_FULFILLMENT_NEW (
    CONFIG_ID                INTEGER NOT NULL,
    MODULE_ID                TEXT    NOT NULL,
    REQUIREMENT_NAME         TEXT    NOT NULL,
    REQUIREMENT_INDEX        INTEGER NOT NULL,
    IMPLEMENTATION_ID        TEXT    NOT NULL,
    IMPLEMENTATION_MODULE_ID TEXT    NOT NULL,
    PRIMARY KEY (CONFIG_ID, MODULE_ID, REQUIREMENT_NAME, REQUIREMENT_INDEX),
    FOREIGN KEY (CONFIG_ID, MODULE_ID)                REFERENCES MODULE (CONFIG_ID, ID) ON DELETE CASCADE,
    FOREIGN KEY (CONFIG_ID, IMPLEMENTATION_MODULE_ID) REFERENCES MODULE (CONFIG_ID, ID) ON DELETE CASCADE
);
-- Databases predating this column carry no ordering information, so keep the order they were
-- previously read back in instead of inventing a new one.
INSERT INTO MODULE_FULFILLMENT_NEW
    SELECT 0, MODULE_ID, REQUIREMENT_NAME,
           ROW_NUMBER() OVER (PARTITION BY MODULE_ID, REQUIREMENT_NAME
                              ORDER BY IMPLEMENTATION_ID, IMPLEMENTATION_MODULE_ID) - 1,
           IMPLEMENTATION_ID, IMPLEMENTATION_MODULE_ID
    FROM MODULE_FULFILLMENT;
DROP TABLE MODULE_FULFILLMENT;
ALTER TABLE MODULE_FULFILLMENT_NEW RENAME TO MODULE_FULFILLMENT;

-- 5. MODULE_TIER_MAPPING: composite FK on (CONFIG_ID, MODULE_ID).
CREATE TABLE MODULE_TIER_MAPPING_NEW (
    CONFIG_ID         INTEGER NOT NULL,
    MODULE_ID         TEXT    NOT NULL,
    IMPLEMENTATION_ID TEXT    NOT NULL,
    EVSE_ID           INTEGER NOT NULL,
    CONNECTOR_ID      INTEGER,
    PRIMARY KEY (CONFIG_ID, MODULE_ID, IMPLEMENTATION_ID),
    FOREIGN KEY (CONFIG_ID, MODULE_ID) REFERENCES MODULE (CONFIG_ID, ID) ON DELETE CASCADE
);
INSERT INTO MODULE_TIER_MAPPING_NEW
    SELECT 0, MODULE_ID, IMPLEMENTATION_ID, EVSE_ID, CONNECTOR_ID
    FROM MODULE_TIER_MAPPING;
DROP TABLE MODULE_TIER_MAPPING;
ALTER TABLE MODULE_TIER_MAPPING_NEW RENAME TO MODULE_TIER_MAPPING;

-- 6. CONFIGURATION: composite FK on (CONFIG_ID, MODULE_ID).
CREATE TABLE CONFIGURATION_NEW (
    CONFIG_ID                INTEGER NOT NULL,
    PARAMETER_NAME           TEXT    NOT NULL,
    MODULE_ID                TEXT    NOT NULL,
    MODULE_IMPLEMENTATION_ID TEXT    NOT NULL,
    "VALUE"                  TEXT    NOT NULL,
    MUTABILITY_ID            INTEGER NOT NULL,
    DATATYPE_ID              INTEGER NOT NULL,
    UNIT                     TEXT,
    SOURCE                   TEXT,
    PRIMARY KEY (CONFIG_ID, MODULE_ID, PARAMETER_NAME, MODULE_IMPLEMENTATION_ID),
    FOREIGN KEY (CONFIG_ID, MODULE_ID) REFERENCES MODULE (CONFIG_ID, ID) ON DELETE CASCADE,
    FOREIGN KEY (DATATYPE_ID)          REFERENCES DATATYPE (ID)  ON DELETE RESTRICT,
    FOREIGN KEY (MUTABILITY_ID)        REFERENCES MUTABILITY (ID) ON DELETE RESTRICT
);
INSERT INTO CONFIGURATION_NEW
    SELECT 0, PARAMETER_NAME, MODULE_ID, MODULE_IMPLEMENTATION_ID, VALUE,
           MUTABILITY_ID, DATATYPE_ID, UNIT, SOURCE
    FROM CONFIGURATION;
DROP TABLE CONFIGURATION;
ALTER TABLE CONFIGURATION_NEW RENAME TO CONFIGURATION;

-- 7. CONFIG_ACCESS: composite FK on (CONFIG_ID, MODULE_ID).
CREATE TABLE CONFIG_ACCESS_NEW (
    CONFIG_ID           INTEGER NOT NULL,
    MODULE_ID           TEXT    NOT NULL,
    ALLOW_GLOBAL_READ   INTEGER,
    ALLOW_GLOBAL_WRITE  INTEGER,
    ALLOW_SET_READ_ONLY INTEGER,
    PRIMARY KEY (CONFIG_ID, MODULE_ID),
    FOREIGN KEY (CONFIG_ID, MODULE_ID) REFERENCES MODULE (CONFIG_ID, ID) ON DELETE CASCADE
);
INSERT INTO CONFIG_ACCESS_NEW
    SELECT 0, MODULE_ID, ALLOW_GLOBAL_READ, ALLOW_GLOBAL_WRITE, ALLOW_SET_READ_ONLY
    FROM CONFIG_ACCESS;
DROP TABLE CONFIG_ACCESS;
ALTER TABLE CONFIG_ACCESS_NEW RENAME TO CONFIG_ACCESS;

-- 8. MODULE_CONFIG_ACCESS: composite FKs on both MODULE_ID and OTHER_MODULE_ID.
CREATE TABLE MODULE_CONFIG_ACCESS_NEW (
    CONFIG_ID           INTEGER NOT NULL,
    MODULE_ID           TEXT    NOT NULL,
    OTHER_MODULE_ID     TEXT    NOT NULL,
    ALLOW_READ          INTEGER,
    ALLOW_WRITE         INTEGER,
    ALLOW_SET_READ_ONLY INTEGER,
    PRIMARY KEY (CONFIG_ID, MODULE_ID, OTHER_MODULE_ID),
    FOREIGN KEY (CONFIG_ID, MODULE_ID)       REFERENCES MODULE (CONFIG_ID, ID) ON DELETE CASCADE,
    FOREIGN KEY (CONFIG_ID, OTHER_MODULE_ID) REFERENCES MODULE (CONFIG_ID, ID) ON DELETE CASCADE
);
INSERT INTO MODULE_CONFIG_ACCESS_NEW
    SELECT 0, MODULE_ID, OTHER_MODULE_ID, ALLOW_READ, ALLOW_WRITE, ALLOW_SET_READ_ONLY
    FROM MODULE_CONFIG_ACCESS;
DROP TABLE MODULE_CONFIG_ACCESS;
ALTER TABLE MODULE_CONFIG_ACCESS_NEW RENAME TO MODULE_CONFIG_ACCESS;

-- 9. BOOT_CONFIG: single-row table storing next-boot slot selection.
-- Only an *explicit* selection is stored; the absence of a row means "use slot 0". That is also
-- the bootstrap state of a fresh database, where no CONFIG row exists yet and slot 0 is merely
-- where the first config will be seeded. Because only resolvable selections are ever stored, the
-- foreign key can guarantee the pointer never dangles: deleting a slot that is marked for the
-- next boot is rejected (RESTRICT) instead of silently leaving the selection pointing at nothing.
--
-- The ID column exists to make UPSERT operations possible (ID in the ON CONFLICT target)
CREATE TABLE BOOT_CONFIG (
    ID                INTEGER PRIMARY KEY CHECK (ID = 0),
    NEXT_BOOT_SLOT_ID INTEGER NOT NULL REFERENCES CONFIG (ID) ON DELETE RESTRICT
);
-- Upgraded databases carry their original config at slot 0, so there is something valid to point
-- at. Fresh databases have an empty CONFIG at this point and stay deliberately row-less.
INSERT INTO BOOT_CONFIG (ID, NEXT_BOOT_SLOT_ID) SELECT 0, ID FROM CONFIG WHERE ID = 0;

-- 10. MUTABILITY and DATATYPE: Fix ordering to match the framework library enum definition.
INSERT OR REPLACE INTO MUTABILITY (ID, MUTABILITY) VALUES 
  (1, "ReadWrite"),
  (2, "WriteOnly");
INSERT
  OR REPLACE INTO DATATYPE VALUES 
  (0, "unknown"),
  (1, "string"),
  (2, "decimal"),
  (3, "integer"),
  (4, "boolean");
