CREATE TABLE SESSIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SESSION_ID TEXT NOT NULL UNIQUE,
    OCPP_TRANSACTION_ID TEXT,
    OCPP_TRANSACTION_TIMESTAMP_START TEXT,
    OCPP_TRANSACTION_TIMESTAMP_STOP TEXT,
    EVSE_ID INTEGER NOT NULL,
    EVSE_ID_STRING TEXT NOT NULL DEFAULT '',
    CONNECTOR_ID INTEGER NOT NULL DEFAULT 1,
    STATE TEXT NOT NULL CHECK (STATE IN ('Open', 'Finished', 'Stale')),
    TIMESTAMP_START TEXT NOT NULL,
    START_REASON TEXT NOT NULL,
    TIMESTAMP_STOP TEXT,
    TRANSACTION_TIMESTAMP_START TEXT,
    TRANSACTION_TIMESTAMP_STOP TEXT,
    ENERGY_WH_IMPORT_START REAL,
    ENERGY_WH_IMPORT_STOP REAL,
    ID_TOKEN_HASH TEXT,
    ID_TOKEN_TYPE TEXT,
    AUTHORIZATION_TYPE TEXT,
    STOP_REASON TEXT,
    SIGNED_METER_VALUE_START TEXT,
    SIGNED_METER_VALUE_STOP TEXT,
    COST TEXT
);

CREATE TABLE METADATA (
    KEY TEXT PRIMARY KEY,
    VALUE TEXT NOT NULL
);

INSERT INTO METADATA (KEY, VALUE) VALUES ('EPOCH', lower(hex(randomblob(8))));

CREATE INDEX IX_SESSIONS_OCPP_TRANSACTION_ID ON SESSIONS (OCPP_TRANSACTION_ID);

CREATE INDEX IX_SESSIONS_EVSE_ID_STATE ON SESSIONS (EVSE_ID, STATE);
