"""Starlark representation of locked requirements.

@generated by rules_python pip.parse bzlmod extension.
"""

load("@rules_python//python:pip.bzl", "pip_utils")

all_requirements = [
    "@@rules_python++pip+everest-testing_pip_deps//attrs:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//cffi:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//cryptography:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//exceptiongroup:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//importlib_resources:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//iniconfig:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//jinja2:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//jsonschema:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//jsonschema_specifications:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//markupsafe:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//ocpp:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//packaging:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//paho_mqtt:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pkgutil_resolve_name:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pluggy:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pycparser:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pyftpdlib:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pyopenssl:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pyrsistent:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pytest:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pytest_asyncio:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//python_dateutil:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pyyaml:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//referencing:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//rpds_py:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//six:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//stringcase:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//tomli:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//websockets:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//zipp:pkg",
]

all_whl_requirements_by_package = {
    "attrs": "@@rules_python++pip+everest-testing_pip_deps//attrs:whl",
    "cffi": "@@rules_python++pip+everest-testing_pip_deps//cffi:whl",
    "cryptography": "@@rules_python++pip+everest-testing_pip_deps//cryptography:whl",
    "exceptiongroup": "@@rules_python++pip+everest-testing_pip_deps//exceptiongroup:whl",
    "importlib_resources": "@@rules_python++pip+everest-testing_pip_deps//importlib_resources:whl",
    "iniconfig": "@@rules_python++pip+everest-testing_pip_deps//iniconfig:whl",
    "jinja2": "@@rules_python++pip+everest-testing_pip_deps//jinja2:whl",
    "jsonschema": "@@rules_python++pip+everest-testing_pip_deps//jsonschema:whl",
    "jsonschema_specifications": "@@rules_python++pip+everest-testing_pip_deps//jsonschema_specifications:whl",
    "markupsafe": "@@rules_python++pip+everest-testing_pip_deps//markupsafe:whl",
    "ocpp": "@@rules_python++pip+everest-testing_pip_deps//ocpp:whl",
    "packaging": "@@rules_python++pip+everest-testing_pip_deps//packaging:whl",
    "paho_mqtt": "@@rules_python++pip+everest-testing_pip_deps//paho_mqtt:whl",
    "pkgutil_resolve_name": "@@rules_python++pip+everest-testing_pip_deps//pkgutil_resolve_name:whl",
    "pluggy": "@@rules_python++pip+everest-testing_pip_deps//pluggy:whl",
    "pycparser": "@@rules_python++pip+everest-testing_pip_deps//pycparser:whl",
    "pyftpdlib": "@@rules_python++pip+everest-testing_pip_deps//pyftpdlib:whl",
    "pyopenssl": "@@rules_python++pip+everest-testing_pip_deps//pyopenssl:whl",
    "pyrsistent": "@@rules_python++pip+everest-testing_pip_deps//pyrsistent:whl",
    "pytest": "@@rules_python++pip+everest-testing_pip_deps//pytest:whl",
    "pytest_asyncio": "@@rules_python++pip+everest-testing_pip_deps//pytest_asyncio:whl",
    "python_dateutil": "@@rules_python++pip+everest-testing_pip_deps//python_dateutil:whl",
    "pyyaml": "@@rules_python++pip+everest-testing_pip_deps//pyyaml:whl",
    "referencing": "@@rules_python++pip+everest-testing_pip_deps//referencing:whl",
    "rpds_py": "@@rules_python++pip+everest-testing_pip_deps//rpds_py:whl",
    "six": "@@rules_python++pip+everest-testing_pip_deps//six:whl",
    "stringcase": "@@rules_python++pip+everest-testing_pip_deps//stringcase:whl",
    "tomli": "@@rules_python++pip+everest-testing_pip_deps//tomli:whl",
    "websockets": "@@rules_python++pip+everest-testing_pip_deps//websockets:whl",
    "zipp": "@@rules_python++pip+everest-testing_pip_deps//zipp:whl",
}

all_whl_requirements = all_whl_requirements_by_package.values()

all_data_requirements = [
    "@@rules_python++pip+everest-testing_pip_deps//attrs:data",
    "@@rules_python++pip+everest-testing_pip_deps//cffi:data",
    "@@rules_python++pip+everest-testing_pip_deps//cryptography:data",
    "@@rules_python++pip+everest-testing_pip_deps//exceptiongroup:data",
    "@@rules_python++pip+everest-testing_pip_deps//importlib_resources:data",
    "@@rules_python++pip+everest-testing_pip_deps//iniconfig:data",
    "@@rules_python++pip+everest-testing_pip_deps//jinja2:data",
    "@@rules_python++pip+everest-testing_pip_deps//jsonschema:data",
    "@@rules_python++pip+everest-testing_pip_deps//jsonschema_specifications:data",
    "@@rules_python++pip+everest-testing_pip_deps//markupsafe:data",
    "@@rules_python++pip+everest-testing_pip_deps//ocpp:data",
    "@@rules_python++pip+everest-testing_pip_deps//packaging:data",
    "@@rules_python++pip+everest-testing_pip_deps//paho_mqtt:data",
    "@@rules_python++pip+everest-testing_pip_deps//pkgutil_resolve_name:data",
    "@@rules_python++pip+everest-testing_pip_deps//pluggy:data",
    "@@rules_python++pip+everest-testing_pip_deps//pycparser:data",
    "@@rules_python++pip+everest-testing_pip_deps//pyftpdlib:data",
    "@@rules_python++pip+everest-testing_pip_deps//pyopenssl:data",
    "@@rules_python++pip+everest-testing_pip_deps//pyrsistent:data",
    "@@rules_python++pip+everest-testing_pip_deps//pytest:data",
    "@@rules_python++pip+everest-testing_pip_deps//pytest_asyncio:data",
    "@@rules_python++pip+everest-testing_pip_deps//python_dateutil:data",
    "@@rules_python++pip+everest-testing_pip_deps//pyyaml:data",
    "@@rules_python++pip+everest-testing_pip_deps//referencing:data",
    "@@rules_python++pip+everest-testing_pip_deps//rpds_py:data",
    "@@rules_python++pip+everest-testing_pip_deps//six:data",
    "@@rules_python++pip+everest-testing_pip_deps//stringcase:data",
    "@@rules_python++pip+everest-testing_pip_deps//tomli:data",
    "@@rules_python++pip+everest-testing_pip_deps//websockets:data",
    "@@rules_python++pip+everest-testing_pip_deps//zipp:data",
]

def requirement(name):
    return "@@rules_python++pip+everest-testing_pip_deps//{}:{}".format(pip_utils.normalize_name(name), "pkg")

def whl_requirement(name):
    return "@@rules_python++pip+everest-testing_pip_deps//{}:{}".format(pip_utils.normalize_name(name), "whl")

def data_requirement(name):
    return "@@rules_python++pip+everest-testing_pip_deps//{}:{}".format(pip_utils.normalize_name(name), "data")

def dist_info_requirement(name):
    return "@@rules_python++pip+everest-testing_pip_deps//{}:{}".format(pip_utils.normalize_name(name), "dist_info")
