"""Starlark representation of locked requirements.

@generated by rules_python pip.parse bzlmod extension.
"""

load("@rules_python//python:pip.bzl", "pip_utils")

all_requirements = [
    "@@rules_python++pip+everest-testing_pip_deps//attrs:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//certifi:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//cffi:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//charset_normalizer:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//cryptography:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//execnet:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//idna:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//iniconfig:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//jinja2:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//jsonschema:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//jsonschema_specifications:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//markupsafe:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//ocpp:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//packaging:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//paho_mqtt:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pluggy:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pyasynchat:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pyasyncore:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pycparser:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pyftpdlib:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pygments:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pytest:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pytest_asyncio:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pytest_html:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pytest_metadata:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pytest_rerunfailures:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pytest_timeout:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pytest_xdist:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//python_dateutil:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//pyyaml:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//referencing:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//requests:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//rpds_py:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//six:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//stringcase:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//typing_extensions:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//urllib3:pkg",
    "@@rules_python++pip+everest-testing_pip_deps//websockets:pkg",
]

all_whl_requirements_by_package = {
    "attrs": "@@rules_python++pip+everest-testing_pip_deps//attrs:whl",
    "certifi": "@@rules_python++pip+everest-testing_pip_deps//certifi:whl",
    "cffi": "@@rules_python++pip+everest-testing_pip_deps//cffi:whl",
    "charset_normalizer": "@@rules_python++pip+everest-testing_pip_deps//charset_normalizer:whl",
    "cryptography": "@@rules_python++pip+everest-testing_pip_deps//cryptography:whl",
    "execnet": "@@rules_python++pip+everest-testing_pip_deps//execnet:whl",
    "idna": "@@rules_python++pip+everest-testing_pip_deps//idna:whl",
    "iniconfig": "@@rules_python++pip+everest-testing_pip_deps//iniconfig:whl",
    "jinja2": "@@rules_python++pip+everest-testing_pip_deps//jinja2:whl",
    "jsonschema": "@@rules_python++pip+everest-testing_pip_deps//jsonschema:whl",
    "jsonschema_specifications": "@@rules_python++pip+everest-testing_pip_deps//jsonschema_specifications:whl",
    "markupsafe": "@@rules_python++pip+everest-testing_pip_deps//markupsafe:whl",
    "ocpp": "@@rules_python++pip+everest-testing_pip_deps//ocpp:whl",
    "packaging": "@@rules_python++pip+everest-testing_pip_deps//packaging:whl",
    "paho_mqtt": "@@rules_python++pip+everest-testing_pip_deps//paho_mqtt:whl",
    "pluggy": "@@rules_python++pip+everest-testing_pip_deps//pluggy:whl",
    "pyasynchat": "@@rules_python++pip+everest-testing_pip_deps//pyasynchat:whl",
    "pyasyncore": "@@rules_python++pip+everest-testing_pip_deps//pyasyncore:whl",
    "pycparser": "@@rules_python++pip+everest-testing_pip_deps//pycparser:whl",
    "pyftpdlib": "@@rules_python++pip+everest-testing_pip_deps//pyftpdlib:whl",
    "pygments": "@@rules_python++pip+everest-testing_pip_deps//pygments:whl",
    "pytest": "@@rules_python++pip+everest-testing_pip_deps//pytest:whl",
    "pytest_asyncio": "@@rules_python++pip+everest-testing_pip_deps//pytest_asyncio:whl",
    "pytest_html": "@@rules_python++pip+everest-testing_pip_deps//pytest_html:whl",
    "pytest_metadata": "@@rules_python++pip+everest-testing_pip_deps//pytest_metadata:whl",
    "pytest_rerunfailures": "@@rules_python++pip+everest-testing_pip_deps//pytest_rerunfailures:whl",
    "pytest_timeout": "@@rules_python++pip+everest-testing_pip_deps//pytest_timeout:whl",
    "pytest_xdist": "@@rules_python++pip+everest-testing_pip_deps//pytest_xdist:whl",
    "python_dateutil": "@@rules_python++pip+everest-testing_pip_deps//python_dateutil:whl",
    "pyyaml": "@@rules_python++pip+everest-testing_pip_deps//pyyaml:whl",
    "referencing": "@@rules_python++pip+everest-testing_pip_deps//referencing:whl",
    "requests": "@@rules_python++pip+everest-testing_pip_deps//requests:whl",
    "rpds_py": "@@rules_python++pip+everest-testing_pip_deps//rpds_py:whl",
    "six": "@@rules_python++pip+everest-testing_pip_deps//six:whl",
    "stringcase": "@@rules_python++pip+everest-testing_pip_deps//stringcase:whl",
    "typing_extensions": "@@rules_python++pip+everest-testing_pip_deps//typing_extensions:whl",
    "urllib3": "@@rules_python++pip+everest-testing_pip_deps//urllib3:whl",
    "websockets": "@@rules_python++pip+everest-testing_pip_deps//websockets:whl",
}

all_whl_requirements = all_whl_requirements_by_package.values()

all_data_requirements = [
    "@@rules_python++pip+everest-testing_pip_deps//attrs:data",
    "@@rules_python++pip+everest-testing_pip_deps//certifi:data",
    "@@rules_python++pip+everest-testing_pip_deps//cffi:data",
    "@@rules_python++pip+everest-testing_pip_deps//charset_normalizer:data",
    "@@rules_python++pip+everest-testing_pip_deps//cryptography:data",
    "@@rules_python++pip+everest-testing_pip_deps//execnet:data",
    "@@rules_python++pip+everest-testing_pip_deps//idna:data",
    "@@rules_python++pip+everest-testing_pip_deps//iniconfig:data",
    "@@rules_python++pip+everest-testing_pip_deps//jinja2:data",
    "@@rules_python++pip+everest-testing_pip_deps//jsonschema:data",
    "@@rules_python++pip+everest-testing_pip_deps//jsonschema_specifications:data",
    "@@rules_python++pip+everest-testing_pip_deps//markupsafe:data",
    "@@rules_python++pip+everest-testing_pip_deps//ocpp:data",
    "@@rules_python++pip+everest-testing_pip_deps//packaging:data",
    "@@rules_python++pip+everest-testing_pip_deps//paho_mqtt:data",
    "@@rules_python++pip+everest-testing_pip_deps//pluggy:data",
    "@@rules_python++pip+everest-testing_pip_deps//pyasynchat:data",
    "@@rules_python++pip+everest-testing_pip_deps//pyasyncore:data",
    "@@rules_python++pip+everest-testing_pip_deps//pycparser:data",
    "@@rules_python++pip+everest-testing_pip_deps//pyftpdlib:data",
    "@@rules_python++pip+everest-testing_pip_deps//pygments:data",
    "@@rules_python++pip+everest-testing_pip_deps//pytest:data",
    "@@rules_python++pip+everest-testing_pip_deps//pytest_asyncio:data",
    "@@rules_python++pip+everest-testing_pip_deps//pytest_html:data",
    "@@rules_python++pip+everest-testing_pip_deps//pytest_metadata:data",
    "@@rules_python++pip+everest-testing_pip_deps//pytest_rerunfailures:data",
    "@@rules_python++pip+everest-testing_pip_deps//pytest_timeout:data",
    "@@rules_python++pip+everest-testing_pip_deps//pytest_xdist:data",
    "@@rules_python++pip+everest-testing_pip_deps//python_dateutil:data",
    "@@rules_python++pip+everest-testing_pip_deps//pyyaml:data",
    "@@rules_python++pip+everest-testing_pip_deps//referencing:data",
    "@@rules_python++pip+everest-testing_pip_deps//requests:data",
    "@@rules_python++pip+everest-testing_pip_deps//rpds_py:data",
    "@@rules_python++pip+everest-testing_pip_deps//six:data",
    "@@rules_python++pip+everest-testing_pip_deps//stringcase:data",
    "@@rules_python++pip+everest-testing_pip_deps//typing_extensions:data",
    "@@rules_python++pip+everest-testing_pip_deps//urllib3:data",
    "@@rules_python++pip+everest-testing_pip_deps//websockets:data",
]

def requirement(name):
    return "@@rules_python++pip+everest-testing_pip_deps//{}:{}".format(pip_utils.normalize_name(name), "pkg")

def whl_requirement(name):
    return "@@rules_python++pip+everest-testing_pip_deps//{}:{}".format(pip_utils.normalize_name(name), "whl")

def data_requirement(name):
    return "@@rules_python++pip+everest-testing_pip_deps//{}:{}".format(pip_utils.normalize_name(name), "data")

def dist_info_requirement(name):
    return "@@rules_python++pip+everest-testing_pip_deps//{}:{}".format(pip_utils.normalize_name(name), "dist_info")
