load("//applications/utils:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary", "py_library")
load("//third-party/bazel/toolchains:defs.bzl", "CROSS_PYTHON_INCOMPATIBLE")

exports_files(
    ["BUILD.bazel"],
)

py_library(
    name = "lib",
    srcs = glob(["src/everest_api_client_gen/*.py"]),
    imports = ["src"],
    target_compatible_with = CROSS_PYTHON_INCOMPATIBLE,
    deps = [
        requirement("jinja2"),
        requirement("pyyaml"),
    ],
)

py_binary(
    name = "everest-api-client-gen",
    srcs = ["src/everest_api_client_gen/cli.py"],
    data = glob(["src/everest_api_client_gen/templates/**"]),
    legacy_create_init = False,
    main = "src/everest_api_client_gen/cli.py",
    visibility = ["//visibility:public"],
    target_compatible_with = CROSS_PYTHON_INCOMPATIBLE,
    deps = [":lib"],
)
