[metadata]
name = everest-api-client-gen
version = attr: everest_api_client_gen.__version__
description = Generator for the EVerest API Python MQTT clients (npm-free)
long_description = file: README.rst
long_description_content_type = text/x-rst
url = https://github.com/EVerest/everest-core
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: Apache Software License
    Operating System :: OS Independent

[options]
install_requires =
    jinja2 ~=3.1
    pyyaml ~=6.0
package_dir =
    = src
packages = everest_api_client_gen
python_requires = >=3.8

[options.entry_points]
console_scripts =
    everest-api-client-gen = everest_api_client_gen.cli:main

[options.package_data]
everest_api_client_gen =
    templates/*.j2
