#!/usr/bin/env python3
#
# SPDX-License-Identifier: Apache-2.0
# Copyright Pionix GmbH and Contributors to EVerest
"""Keep the build-kit's baked test requirements in step with everest-testing.

The OCPP and integration jobs pip-install the locally built everest-testing
wheel into the build-kit image on every run. Its third-party requirements are
resolved from PyPI unless the image already satisfies them, which puts a PyPI
fetch on the critical path of every one of those jobs. Baking the same
requirements into the image turns that resolution into a no-op.

Run without arguments to refresh the requirements file, or with --check to fail
when it has drifted from setup.cfg, which is what CI does.
"""

import argparse
import configparser
import difflib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SETUP_CFG = REPO_ROOT / "applications/utils/everest-testing/setup.cfg"
REQUIREMENTS = REPO_ROOT / ".ci/build-kit/docker/test-requirements.txt"

HEADER = f"""# Generated by {Path(__file__).relative_to(REPO_ROOT)}. Do not edit.
#
# Third-party requirements of {SETUP_CFG.relative_to(REPO_ROOT)}, baked into the
# build-kit image so that installing the everest-testing wheel in a test job
# resolves them from the image instead of downloading them from PyPI.
"""


def render():
    parser = configparser.ConfigParser()
    parser.read(SETUP_CFG)
    requirements = parser["options"]["install_requires"].strip().splitlines()
    return HEADER + "".join(f"{r.strip()}\n" for r in requirements)


def main():
    args = argparse.ArgumentParser(description=__doc__)
    args.add_argument("--check", action="store_true", help="fail if out of date")
    if not args.parse_args().check:
        REQUIREMENTS.write_text(render())
        return 0

    current = REQUIREMENTS.read_text() if REQUIREMENTS.exists() else ""
    if current == render():
        return 0
    sys.stderr.writelines(
        difflib.unified_diff(
            current.splitlines(keepends=True),
            render().splitlines(keepends=True),
            fromfile=str(REQUIREMENTS.relative_to(REPO_ROOT)),
            tofile="expected",
        )
    )
    sys.stderr.write(
        f"\n{REQUIREMENTS.relative_to(REPO_ROOT)} is out of date, "
        f"run {Path(__file__).relative_to(REPO_ROOT)} to refresh it\n"
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
