# SPDX-License-Identifier: Apache-2.0
# Copyright Pionix GmbH and Contributors to EVerest
"""The C++ backend.

Everything that knows C++ lives under this package: the type mapping, the
naming conventions and the templates.  The templates render from the IR
directly, through the view in :mod:`.view`.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import jinja2

from ... import blocks
from ...files import clang_format
from ...ir.model import Model
from ..base import GeneratedFile, UpdatePolicy
from . import naming
from .view import (
    TEMPLATE_VERSION,
    ImplementationView,
    InterfaceView,
    ModuleView,
    TypeUnitView,
)

TEMPLATE_DIR = Path(__file__).parent / 'templates'

#: Which templates back which command, for ``get-templates``.  CMake stores the
#: result as a dependency, so a template edit has to appear here or edits to it
#: will not trigger regeneration.
TEMPLATES_BY_SCOPE: dict[str, tuple[str, ...]] = {
    'types': ('types.hpp.j2',),
    'interface': (
        'interface-Implementation.hpp.j2',
        'interface-Interface.hpp.j2',
        'interface-Types.hpp.j2',
    ),
    'module': ('ld-ev.hpp.j2', 'ld-ev.cpp.j2'),
    # The skeleton sources 'module create' writes.  Deliberately not part of
    # 'module get-templates': CMake uses that to decide when to regenerate the
    # loader, and these files are never regenerated by a build.
    'module_files': (
        'CMakeLists.txt.j2',
        'module.hpp.j2',
        'module.cpp.j2',
        'implementation.hpp.j2',
        'implementation.cpp.j2',
        'docs-index.rst.j2',
    ),
}


class CppBackend:
    """Generates the C++ headers everest-core's modules compile against."""

    name = 'cpp'

    @staticmethod
    def options() -> argparse.ArgumentParser:
        """Formatting the generated sources is this target's business alone.

        Both options keep their historical names: EVerest's build passes
        ``--disable-clang-format`` and the spelling is part of the contract.
        """
        parser = argparse.ArgumentParser(add_help=False)
        group = parser.add_argument_group('cpp backend')
        group.add_argument(
            '--clang-format-file', type=str, default=str(Path.cwd()),
            help='directory containing the .clang-format file (default: .)')
        group.add_argument(
            '--disable-clang-format', action='store_true', default=False,
            help='do not run clang-format over generated sources')
        return parser

    def __init__(self, args=None) -> None:
        self._clang_format_dir = Path(getattr(args, 'clang_format_file', None) or Path.cwd())
        self._disable_clang_format = bool(getattr(args, 'disable_clang_format', False))
        self._env = jinja2.Environment(
            loader=jinja2.FileSystemLoader(TEMPLATE_DIR),
            lstrip_blocks=True,
            trim_blocks=True,
            keep_trailing_newline=True,
            undefined=jinja2.StrictUndefined,
        )
        self._env.filters['snake_case'] = naming.snake_case

    # -- post-processing ----------------------------------------------------

    def postprocess(self, files: list[GeneratedFile]) -> None:
        """Format the generated sources.

        The commands do not know that C++ needs formatting, or which of a
        target's outputs are even C++; clang_format itself skips anything that
        is not a .hpp or a .cpp.
        """
        if self._disable_clang_format:
            return
        for file in files:
            clang_format(self._clang_format_dir, file)

    # -- templates ----------------------------------------------------------

    def templates(self, scope: str = 'all') -> list[Path]:
        names: tuple[str, ...]
        if scope == 'all':
            names = tuple(n for group in TEMPLATES_BY_SCOPE.values() for n in group)
        else:
            names = TEMPLATES_BY_SCOPE[scope]
        # Only the ones present, so that a partially built backend still has a
        # working command line rather than pointing CMake at a missing file.
        return [TEMPLATE_DIR / name for name in names if (TEMPLATE_DIR / name).exists()]

    def _template_paths(self, scope: str) -> tuple[Path, ...]:
        return tuple(self.templates(scope))

    # -- emission -----------------------------------------------------------

    def emit_type_unit(self, model: Model, unit: str, output_dir: Path) -> list[GeneratedFile]:
        view = TypeUnitView(unit=model.types[unit], model=model)
        content = self._env.get_template('types.hpp.j2').render(u=view)

        path = output_dir / f'{unit}.hpp'
        return [GeneratedFile(
            path=path,
            content=content,
            # Matches what the build logs today: the output directory's own name
            # followed by the unit, e.g. "types/energy.hpp".
            printable_name=(Path(output_dir.name) / f'{unit}.hpp').as_posix(),
            # Deliberately the unit's own modification time, not the newest
            # among the units it references.  That is what the previous
            # generator compared against and what EVerest's incremental builds
            # are tuned for; widening it is a separate change.
            source_mtime=view.unit.source.file.stat().st_mtime,
            template_paths=self._template_paths('types'),
            category='types',
            abbr=f'{unit}.hpp',
        )]

    def emit_interface(self, model: Model, interface: str, output_dir: Path) -> list[GeneratedFile]:
        view = InterfaceView(interface=model.interfaces[interface], model=model)
        output_path = output_dir / interface
        mtime = view.interface.source.file.stat().st_mtime
        templates = self._template_paths('interface')

        # All three are declared as genrule outputs in interfaces/BUILD.bazel,
        # so all three have to be produced for every interface.
        outputs = (
            ('Implementation.hpp', 'interface-Implementation.hpp.j2'),
            ('Interface.hpp', 'interface-Interface.hpp.j2'),
            ('Types.hpp', 'interface-Types.hpp.j2'),
        )
        return [
            GeneratedFile(
                path=output_path / filename,
                content=self._env.get_template(template).render(u=view),
                printable_name=f'{interface}/{filename}',
                source_mtime=mtime,
                template_paths=templates,
                category='interfaces',
                abbr=f'{interface}/{filename}',
            )
            for filename, template in outputs
        ]

    def emit_module_loader(self, model: Model, module: str, output_dir: Path) -> list[GeneratedFile]:
        definition = model.modules[module]
        view = ModuleView(module=definition, model=model)
        # Modules are addressed by path but their generated sources sit under
        # the last segment of it.
        name = definition.name
        mtime = definition.source.file.stat().st_mtime
        templates = self._template_paths('module')

        return [
            GeneratedFile(
                path=output_dir / name / filename,
                content=self._env.get_template(template).render(u=view),
                printable_name=f'{name}/{filename}',
                source_mtime=mtime,
                template_paths=templates,
                category='core',
                abbr=filename,
            )
            for filename, template in (
                ('ld-ev.hpp', 'ld-ev.hpp.j2'),
                ('ld-ev.cpp', 'ld-ev.cpp.j2'),
            )
        ]

    def emit_module_files(
        self,
        model: Model,
        module: str,
        module_dir: Path,
        *,
        license_header: str,
        read_blocks,
    ) -> list[GeneratedFile]:
        """The sources ``module create`` and ``module update`` manage.

        ``read_blocks`` is handed in rather than looked up here: which regions
        a file protects is a property of the template, and so belongs to this
        backend, but whether an existing file should be read back is the
        command's decision.
        """
        definition = model.modules[module]
        mtime = definition.source.file.stat().st_mtime
        templates = self._template_paths('module_files')

        def rendered(template: str, view, path: Path, abbr: str, category: str,
                     policy: UpdatePolicy = UpdatePolicy.REGENERATE,
                     with_license: bool = True) -> GeneratedFile:
            return GeneratedFile(
                path=path,
                content=self._env.get_template(template).render(u=view),
                printable_name=path.relative_to(module_dir).as_posix(),
                source_mtime=mtime,
                template_paths=templates,
                abbr=abbr,
                category=category,
                update_policy=policy,
                license_header=license_header if with_license else None,
            )

        files: list[GeneratedFile] = []

        # -- core -----------------------------------------------------------
        cmakelists = module_dir / 'CMakeLists.txt'
        header = module_dir / f'{definition.name}.hpp'

        files.append(rendered(
            'CMakeLists.txt.j2',
            ModuleView(module=definition, model=model,
                       blocks=read_blocks(blocks.CMAKELISTS, cmakelists)),
            cmakelists, 'cmakelists', 'core', with_license=False,
        ))
        files.append(rendered(
            'module.hpp.j2',
            ModuleView(module=definition, model=model, license_header=license_header,
                       blocks=read_blocks(blocks.MODULE_HEADER, header)),
            header, 'module.hpp', 'core',
        ))
        files.append(rendered(
            'module.cpp.j2',
            ModuleView(module=definition, model=model, license_header=license_header),
            module_dir / f'{definition.name}.cpp', 'module.cpp', 'core',
            UpdatePolicy.CREATE_IF_MISSING,
        ))

        # -- one implementation per provided interface ----------------------
        for provided in definition.provides:
            interface = model.interfaces[provided.interface]
            implementation_header = module_dir / f'{provided.id}/{provided.interface}Impl.hpp'
            view = ImplementationView(
                provided=provided, interface=interface, module=definition,
                model=model, license_header=license_header,
                blocks=read_blocks(blocks.IMPLEMENTATION_HEADER, implementation_header),
            )
            files.append(rendered(
                'implementation.hpp.j2', view, implementation_header,
                f'{provided.id}.hpp', 'interfaces',
            ))
            files.append(rendered(
                'implementation.cpp.j2', view,
                module_dir / f'{provided.id}/{provided.interface}Impl.cpp',
                f'{provided.id}.cpp', 'interfaces',
                UpdatePolicy.CREATE_IF_MISSING,
            ))

        # -- docs -----------------------------------------------------------
        files.append(rendered(
            'docs-index.rst.j2',
            ModuleView(module=definition, model=model),
            module_dir / 'docs' / 'index.rst', 'index.rst', 'docs',
            UpdatePolicy.LEAVE_ALONE, with_license=False,
        ))

        return files
