/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "phyverso.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(EverestToMcu, EverestToMcu, AUTO)


PB_BIND(McuToEverest, McuToEverest, AUTO)


PB_BIND(ErrorFlags, ErrorFlags, AUTO)


PB_BIND(KeepAlive, KeepAlive, AUTO)


PB_BIND(Telemetry, Telemetry, AUTO)


PB_BIND(FanState, FanState, AUTO)


PB_BIND(CoilState, CoilState, AUTO)


PB_BIND(BootConfigRequest, BootConfigRequest, AUTO)


PB_BIND(BootConfigResponse, BootConfigResponse, AUTO)


PB_BIND(ChargePortConfig, ChargePortConfig, AUTO)


PB_BIND(ConfigMotorLockType, ConfigMotorLockType, AUTO)


PB_BIND(RcdCommand, RcdCommand, AUTO)












