load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "everest_api_types",
    srcs = glob(["src/**/*.cpp"]),
    hdrs = glob([
        "include/**/*.hpp",
        "include/**/*.inc",
        "private_include/**/*.hpp",
    ]),
    copts = [
        "-std=c++17",
    ],
    includes = [
        "include",
        "include/everest_api_types",
        "private_include",
        "private_include/everest_api_types",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//types:types_lib",
        "@com_github_nlohmann_json//:json",
    ],
)
