load("//applications/utils:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary", "py_library")
load("//third-party/bazel/toolchains:defs.bzl", "CROSS_PYTHON_INCOMPATIBLE")

exports_files(
    ["BUILD.bazel"],
)

py_library(
    name = "lib",
    srcs = glob(["src/ev_cli/**/*.py"]),
    data = glob([
        "src/ev_cli/backends/*/templates/**",
        "src/ev_cli/licenses/**",
    ]),
    imports = ["src"],
    target_compatible_with = CROSS_PYTHON_INCOMPATIBLE,
    deps = [
        requirement("jinja2"),
        requirement("jsonschema"),
        requirement("pyyaml"),
    ],
)

py_binary(
    name = "ev-cli",
    srcs = ["src/ev_cli/__main__.py"],
    legacy_create_init = False,
    main = "src/ev_cli/__main__.py",
    target_compatible_with = CROSS_PYTHON_INCOMPATIBLE,
    visibility = ["//visibility:public"],
    deps = [":lib"],
)
