/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "yeti.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(EverestToMcu, EverestToMcu, 2)


PB_BIND(McuToEverest, McuToEverest, 2)


PB_BIND(ErrorFlags, ErrorFlags, AUTO)


PB_BIND(KeepAliveLo, KeepAliveLo, AUTO)


PB_BIND(KeepAlive, KeepAlive, AUTO)


PB_BIND(Telemetry, Telemetry, AUTO)


PB_BIND(PowerMeter, PowerMeter, AUTO)


PB_BIND(FirmwareUpdate, FirmwareUpdate, AUTO)







