@startuml

!pragma teoz true
participant CSMS order 10
participant libocpp order 20
participant ComposedDeviceModel order 30
database DeviceModelStorageSqlite order 40
database EverestDeviceModelStorage order 50

autonumber

== Get Device Model at startup ==
libocpp -> ComposedDeviceModel: get_device_model()
loop for each variable
    alt libocpp source
        ComposedDeviceModel -> DeviceModelStorageSqlite: get_value()
    else everest source
        ComposedDeviceModel -> EverestDeviceModelStorage: get_value()
    end
end
ComposedDeviceModel --> libocpp: return model

== SetVariable.req ==
CSMS -> libocpp: SetVariable.req
libocpp -> ComposedDeviceModel: set_value()
alt libocpp source
    ComposedDeviceModel -> DeviceModelStorageSqlite: set_value()
else everest source
    ComposedDeviceModel -> EverestDeviceModelStorage: set_value()
end
ComposedDeviceModel --> libocpp: return status

@enduml