name: Nightly EVerest doc build

on:  
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
jobs:
  nightly-build-and-deploy:
    name: Nightly build and deploy
    uses: ./.github/workflows/build-and-deploy-doc.yml
    with:
      is_release: false
      build_pdf: true
      build_html: true
      deploy_html: true
      # LTODO: change to main
      snapshot_file: everest/everest/snapshots/nightly.yaml@feature/add-doc-preview
      github_pages_repo: everest/everest.github.io@main
      overwrite_existing: true
    secrets:
      SA_GITHUB_SSH_KEY: ${{ secrets.SA_GITHUB_SSH_KEY }}
