name: Nightly EVerest doc build

on:  
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build-docs:
    name: Build sphinx documentation
    uses: ./.github/workflows/build-docs.yml

  deploy-everest-doc:
    name: Deploy EVerest doc
    needs: [build-docs]
    uses: ./.github/workflows/deploy-everest-doc.yml
    with:
      html_artefact_name: ${{ needs.build-docs.outputs.html_artefact_name }}
      is_release: false
      build_pdf: true
      build_html: true
      deploy_html: true
      snapshot_file": everest/everest/main:snapshots/nightly.yaml
      github_pages_repo": everest/everest.github.io
      overwrite_existing": true
