name: Nightly EVerest doc build

on:  
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
  push:
jobs:
  nightly-build-and-deploy:
    name: Nightly build and deploy
    # LTODO: Rename workflow
    uses: ./.github/workflows/deploy-everest-doc.yml
    with:
      is_release: false
      build_pdf: true
      build_html: true
      deploy_html: true
      snapshot_file: everest/everest/snapshots/nightly.yaml@main
      github_pages_repo: everest/everest.github.io@main
      overwrite_existing: true
    secrets:
      SA_GITHUB_SSH_KEY: ${{ secrets.SA_GITHUB_SSH_KEY }}
