name: Nightly EVerest doc build

on:  
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  trigger-doc-build:
    name: Trigger doc build
    strategy:
      matrix:
        os: [ubuntu-20.04]
      max-parallel: 1
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      SA_GITHUB_USERNAME: pionix-compiler
      NIGHTLY_REF: main
      INPUT_IS_RELEASE: false
      INPUT_BUILD_PDF: true
      INPUT_BUILD_HTML: true
      INPUT_DEPLOY_HTML: true
      INPUT_SNAPSHOT_FILE: everest/everest/main:snapshots/nightly.yaml
      INPUT_GITHUB_PAGES_REPO: everest/everest.github.io

    steps:    
      - name: Trigger build with workflow_dispatch
        run: |
          curl \
            -X POST \
            -u "${{ env.SA_GITHUB_USERNAME }}:${{ secrets.SA_GITHUB_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -d '{"ref":"${{ env.NIGHTLY_REF }}","inputs":{"is_release": "${{ env.INPUT_IS_RELASE }}", "build_pdf": "${{ env.INPUT_BUILD_PDF }}", "build_html": "${{ env.INPUT_BUILD_HTML }}", "deploy_html": "${{ env.INPUT_DEPLOY_HTML }}", "snapshot_file": "${{ env.INPUT_SNAPSHOT_FILE }}", "github_pages_repo": "${{ env.INPUT_GITHUB_PAGES_REPO }}"}' \
            https://api.github.com/repos/EVerest/EVerest/actions/workflows/deploy-everest-doc.yml/dispatches
