name: Build and Deploy Documentation
on:
  push:
    tags:
      - '20[0-9][0-9].[0-9][0-9].[0-9]*'

env:
    runner: ubuntu-24.04

jobs:

  setup-env:
    name: Setup Environment
    uses: ./.github/workflows/job_setup-env.yml
    with:
      runner: ${{ env.runner }}
      ref_everest_ci: v1.5.5


  build-build-kit:
    name: Build the build-kit
    needs:
      - setup-env
    uses: ./.github/workflows/job_build-build-kit.yml
    with:
      runner: ${{ env.runner }}
      base_image_tag_everest_ci: ${{ needs.setup-env.outputs.closest_tag_everest_ci }}


  build-docs:
    name: Build and Deploy Documentation
    needs:
      - setup-env
      - build-build-kit
    uses: ./.github/workflows/job_build-docs.yaml
    secrets:
      SA_GITHUB_SSH_KEY: ${{ secrets.SA_GITHUB_SSH_KEY }}
    with:
      runner: ${{ env.runner }}
      is_fork: ${{ needs.setup-env.outputs.is_fork == 'true' }}
      build_kit_artifact_name: ${{ needs.build-build-kit.outputs.build_kit_artifact_name }}
      build_kit_image_tag: ${{ needs.build-build-kit.outputs.build_kit_image_tag }}
      deploy_docs: true
      instance_name: release_${{ github.ref_name }}
      is_release: true
      overwrite_existing_instance: false
