name: PreviewEVerest doc build

on:  
  pull_request:
  workflow_dispatch:
  push:
jobs:
  preview-build-and-deploy:
    name: Preview build and deploy
    uses: ./.github/workflows/build-and-deploy-doc.yml
    with:
      is_release: false
      build_pdf: true
      build_html: true
      deploy_html: true
      github_pages_repo: everest/doc-preview@main
      overwrite_existing: true
      version_name: ${{ github.ref_name }}
    secrets:
      SA_GITHUB_SSH_KEY: ${{ secrets.SA_GITHUB_SSH_KEY }}
